server:
  port: 8000
  servlet:
    context-path: /code_proxy
spring:
  profiles:
    active: dev
  application:
    name: freedom-code
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    deployment-mode:  never-fail # 关闭 SpringAutoDeployment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 258369
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select VERSION()
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  liquibase:
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'
    database-change-log-lock-table: databasechangeloglock
    database-change-log-table: databasechangelog
    drop-first: false
    enabled: false
    test-rollback-on-update: false

  redis:
    database: 3
    host: localhost
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        max-wait: 4000
        min-idle: 6
    port: 6379
    timeout: 4000
# mybatisplus的配置
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    # 对所有的 resultMap 都进行自动映射
    auto-mapping-behavior: full
    # #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0 demo
  try-host: http://localhost:${server.port}

test:
  conditional:
    enabled: false